# Generated by Django 6.0 on 2026-01-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_source_earning"),
    ]

    operations = [
        migrations.AddField(
            model_name="earning",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("in_review", "In Review"),
                    ("accepted", "Accepted"),
                    ("paid", "Paid"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
