# Generated by Django 6.0 on 2026-01-23 03:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_earning_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="earning",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
