# Generated by Django 6.0 on 2026-06-15 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_source_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        help_text="e.g., KCB Checking, M-Pesa Wallet", max_length=100
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("bank", "Bank Account"),
                            ("mobile_money", "Mobile Money (e.g., M-Pesa)"),
                            ("cash", "Cash on Hand"),
                            ("credit", "Credit Card/Loan"),
                        ],
                        default="bank",
                        max_length=20,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional account details like A/C number fragments",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-balance"],
                "unique_together": {("user", "account_name")},
            },
        ),
    ]
