# Generated by Django 6.0 on 2026-06-15 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_accountbalance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountbalance",
            name="account_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="accountbalance",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AccountHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="myapp.accountbalance",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
