# Generated by Django 6.0 on 2026-06-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_alter_accountbalance_account_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountbalance",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("bank", "Bank Account"),
                    ("mobile_money", "Mobile Money (e.g., M-Pesa)"),
                    ("cash", "Cash on Hand"),
                    ("credit", "Credit Card/Loan"),
                    ("jobs", "job accounts"),
                ],
                default="bank",
                max_length=20,
            ),
        ),
    ]
